export const tools = [
  { name: "get_house", description: "Rooms, devices in each room and their current state, plus devices without a room. Call first when you need to know what exists or what is on. Only entities the owner exposed to Bina are listed.", input_schema: { type: "object", properties: {} } },
  { name: "get_state", description: "Full state and attributes of one entity (source list of a TV, volume, battery, etc.).", input_schema: { type: "object", properties: { entity_id: { type: "string" } }, required: ["entity_id"] } },
  { name: "call_service", description: "Run a Home Assistant service. Examples: light.turn_on {brightness_pct:20}; media_player.select_source {source:'YouTube'}; media_player.play_media; media_player.join {group_members:[...]} to sync speakers; climate.set_temperature {temperature:72}; cover.close_cover; lock.lock; alarm_control_panel.alarm_arm_home; scene.turn_on. Protected entities require user confirmation which the system handles.", input_schema: { type: "object", properties: { domain: { type: "string" }, service: { type: "string" }, entity_ids: { type: "array", items: { type: "string" } }, data: { type: "object" } }, required: ["domain", "service", "entity_ids"] } },
  { name: "play_music", description: "Search Spotify and play on a speaker by room. Use for any song, artist, album, playlist or genre request.", input_schema: { type: "object", properties: { query: { type: "string" }, room: { type: "string", description: "room name, e.g. Great Room, Pool" }, volume_pct: { type: "number" } }, required: ["query", "room"] } },
  { name: "get_events", description: "Recent house events: doorbell rings, motion, doors and sliders opening, alarm changes, locks, devices going offline.", input_schema: { type: "object", properties: { hours: { type: "number", default: 24 } } } },
  { name: "describe_camera", description: "Look at a camera right now and describe what is there in one sentence. Works with any camera entity.", input_schema: { type: "object", properties: { entity_id: { type: "string" } }, required: ["entity_id"] } },
  { name: "create_automation", description: "Create a Home Assistant automation for the user to confirm. Build the config object in HA JSON format: {alias, description, mode:'single', triggers:[{trigger:'state', entity_id, to:'on'}], conditions:[], actions:[{action:'light.turn_on', target:{entity_id:[...]}, data:{brightness_pct:50}}]}. Use real entity ids from get_house.", input_schema: { type: "object", properties: { alias: { type: "string" }, summary: { type: "string", description: "one plain sentence for the user" }, config: { type: "object" } }, required: ["alias", "summary", "config"] } },
  { name: "remember", description: "Save a durable fact, nickname or personal scene definition (e.g. 'modo cena = kitchen 60%, dining 40%, soft jazz in great room').", input_schema: { type: "object", properties: { fact: { type: "string" } }, required: ["fact"] } },
  { name: "diagnose", description: "Health of one device: availability, last change, integration. Use when something is not responding.", input_schema: { type: "object", properties: { entity_id: { type: "string" } }, required: ["entity_id"] } }
];
