export const tools = [
  { name: "get_house", description: "Rooms, devices in each room and their current state. Call first when you need to know what exists or what is on.", input_schema: { type: "object", properties: {} } },
  { name: "get_state", description: "Full state and attributes of one entity.", input_schema: { type: "object", properties: { entity_id: { type: "string" } }, required: ["entity_id"] } },
  { name: "call_service", description: "Run a Home Assistant service. Examples: light.turn_on {brightness_pct:20}; media_player.play_media; climate.set_temperature {temperature:72}; cover.close_cover; lock.lock; alarm_control_panel.alarm_arm_home; scene.turn_on. Protected entities require user confirmation which the system handles.", input_schema: { type: "object", properties: { domain: { type: "string" }, service: { type: "string" }, entity_ids: { type: "array", items: { type: "string" } }, data: { type: "object" } }, required: ["domain", "service", "entity_ids"] } },
  { name: "get_events", description: "Recent house events: doors, motion, doorbell, alarm, locks, devices going offline.", input_schema: { type: "object", properties: { hours: { type: "number", default: 24 } } } },
  { name: "describe_camera", description: "Look at a camera right now and describe what is there in one sentence.", input_schema: { type: "object", properties: { entity_id: { type: "string" } }, required: ["entity_id"] } },
  { name: "create_automation", description: "Draft a Home Assistant automation in YAML for the user to confirm. Use when the user describes a routine ('when X happens do Y').", input_schema: { type: "object", properties: { name: { type: "string" }, yaml: { type: "string" }, summary: { type: "string" } }, required: ["name", "yaml", "summary"] } },
  { name: "remember", description: "Save a durable fact about the house or the family (names, preferences, room nicknames).", input_schema: { type: "object", properties: { fact: { type: "string" } }, required: ["fact"] } },
  { name: "diagnose", description: "Health of one device: availability, last change, integration. Use when something is not responding.", input_schema: { type: "object", properties: { entity_id: { type: "string" } }, required: ["entity_id"] } }
];
